version: '3.2'
services:
  php-fpm:
    build: ./php/
    ports:
      - "9000:9000"
    links:
      # - mongodb:mongodb
      - mysql:mysql
      - redis:redis
    volumes:
      - ../:/var/www:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ../logs/php-fpm:/var/log/php-fpm:rw
    restart: always
    command: php-fpm

  nginx:
    build: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../:/var/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    restart: always
    command: nginx -g 'daemon off;'

  # mongo-db:
  #   build: ./mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ../data/mongodb:/data/db
  #   restart: always
  #   # command: "--auth --storageEngine wiredTiger"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: mk123456

  # mongo-express:
  #   build: ./mongo-express
  #   ports: 
  #     - 8081:8081
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mk123456

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql:rw
      - ../logs/mysql:/var/lib/mysql-logs:rw
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mkblog
      MYSQL_USER: mk
      MYSQL_PASSWORD: mk123456
    restart: always
    command: "--character-set-server=utf8"

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always